default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/blog_app_dev.sqlite3

test:
  <<: *default
  database: db/blog_app_test.sqlite3

production:
  <<: *default
  database: db/blog_app_prod.sqlite3
